# Generated by Django 3.0.5 on 2020-04-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('market_place', models.CharField(max_length=50)),
                ('brand_manager', models.CharField(max_length=200)),
                ('brand_associate', models.CharField(max_length=200)),
                ('account_manager', models.CharField(max_length=200)),
                ('shopify_website_uname', models.CharField(max_length=200)),
                ('shopify_website_password', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
