# Generated by Django 3.0.5 on 2020-04-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amz_brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='market_place',
            field=models.CharField(choices=[('US', 'US'), ('UK', 'UK'), ('CA', 'CA'), ('MX', 'MX')], max_length=50),
        ),
    ]
