# Generated by Django 3.0.5 on 2020-04-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amz_brands', '0002_auto_20200419_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='market_place',
            field=models.CharField(max_length=50),
        ),
    ]
