# Generated by Django 3.0.5 on 2020-05-01 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amz_products', '0004_product_prod_brand'),
        ('amz_brands', '0004_auto_20200421_0621'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRemoval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=50)),
                ('order_id', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=200)),
                ('reason_for_removal', models.CharField(choices=[('Obscene Language', 'Obscene Language'), ('Product Review', 'Product Review'), ('Seller PPI included', 'Seller PPI included'), ('Shipment Delays', 'Shipment Delays')], max_length=50)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('brand_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='amz_brands.Brand')),
                ('product_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='amz_products.Product')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
