# Generated by Django 3.0.5 on 2020-05-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amz_sfr_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackremoval',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feedbackremoval',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
