# Generated by Django 3.0.5 on 2020-04-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amz_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_num_of_reviews',
            field=models.IntegerField(),
        ),
    ]
