# Generated by Django 3.0.5 on 2020-04-20 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amz_products', '0002_auto_20200420_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_updated',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
