# Generated by Django 3.0.5 on 2020-04-20 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amz_brands', '0002_auto_20200419_1109'),
        ('amz_products', '0003_product_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_brand',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='amz_brands.Brand'),
        ),
    ]
